export const ADD_COUNTRY = 'ADD_COUNTRY'
export const INCREMENT_COUNTRY_ID = 'INCREMENT_COUNTRY_ID'
export const DECREMENT_COUNTRY_ID = 'DECREMENT_COUNTRY_ID'
export const SELECT_COUNTRY_BY_ID = 'SELECT_COUNTRY_BY_ID'
export const ADD_RATE = 'ADD_RATE'

